### ISSUE TITLE
Long wait state causes multiplier goes wrong.

### ISSUE THREAD

**Issue by rgwan** [twlostow/urv-core#1]
![screenshot-6](https://cloud.githubusercontent.com/assets/1379107/24638812/2d6ca94c-191e-11e7-9520-dcb597c9a0b3.png)

**Comment by twlostow** [comment]
Hey rgvan,

Could you attach the sequence of instructions that causes the error?

Cheers,
Tom

**Comment by rgwan** [comment]
I have a deep modification on this core, includes a compressed decoder, AHB-LITE interface and so on. 

I have solved this bug, and I will push the code to my repository later.

But there 's some other problem on data-bus interface wait state, and I think it probably caused by me on my modification. I will try to fix it by myself.

**Comment by rgwan** [comment]
I fixed it just now, because my compressed-instruction prefetcher drop the instruction during the pipeline is stalled:

![screenshot-9](https://cloud.githubusercontent.com/assets/1379107/24689660/93933650-19fa-11e7-80e1-fce64f182e4f.png)

I will add debug interface (Serial port-based AHB master and a slave inside the core) to this core in 2-3 days.

And I will push the source to my repository:

http://github.com/rgwan/urv-core

Hope you like it.

**Comment by twlostow** [comment]
Hey Zhiyuan,

This is great news! I'll be very glad to integrate your changes into the
official release. Keep me posted, please!

Best,
Tom

2017-04-05 5:31 GMT+02:00 Zhiyuan Wan <notifications@github.com>:

**Comment by rgwan** [comment]
Okay! I will, surely!

Now the divider is working fine....I 'm pending modification on debugging interface and interrupt system.

Zhiyuan

**Comment by rgwan** [comment]
Okay, the new branch amba I was push it to my repository.
